### ISSUE TITLE
Docker install issue ?

### ISSUE THREAD

**Issue by paul-yellowpink** [findy-network/findy-agent#147]
Just following your docker install and seem to be running into the same issue on two different platforms (Docker on MacOS and Ubuntu)

After running docker compose up, the Core and Vault_1 containers fail with the following errors :

Core :

core_1      | State machine db path: /root/findy.bolt 
core_1      | Host address: localhost 
core_1      | Host port: 8080 
core_1      | Server port: 8080 
core_1      | Wallet pool: 10
core_1      | W1221 02:18:25.832214      35 agency.go:132] enclave backup shouldn't be empty in production
core_1      | W1221 02:18:25.832261      35 agency.go:135] wallet backup path shouldn't be empty in production
core_1      | W1221 02:18:25.832333      35 enclave.go:51] init enclave WITHOUT a key /root/.indy_client/enclave.bolt
core_1      | I1221 02:18:25.832410      35 agency.go:184] LoadRegistered kicked to start
core_1      | I1221 02:18:25.832830      35 agency.go:182] LoadRegistered done
core_1      | I1221 02:18:25.832847      35 pool.go:136] convert plugin args for: FINDY_FILE_LEDGER
core_1      | I1221 02:18:25.832855      35 pool.go:149] Using env var defined 2 ledger plugin(s)
core_1      | I1221 02:18:25.832862      35 pool.go:157] Using two ledger plugins
core_1      | I1221 02:18:25.832867      35 pool.go:116] pluginName is NOT legacy
core_1      | I1221 02:18:25.832876      35 memledger.go:114] memLedger reset mem
core_1      | I1221 02:18:25.832895      35 fileledger.go:43] -- file ledger: /root/.indy_client.json
core_1      | I1221 02:18:25.832916      35 pool.go:105] open plugin:FINDY_FILE_LEDGER() ==> OK
core_1      | I1221 02:18:25.832983      35 wallet.go:94] opening wallet: steward
core_1      | I1221 02:18:25.835705      35 findy.go:25] Error: Wallet not found
core_1      |   Caused by: No wallet database exists
core_1      | Error: Error: Wallet not found
core_1      |   Caused by: No wallet database exists
core_1      | 
findy-agent_core_1 exited with code 1

Vault_1 :
vault_1     | I1221 02:18:30.465498      11 config.go:74] Configuration file was not found, using environment/default variables only
vault_1     | I1221 02:18:30.681951      11 pg.go:142] migrations ok: 4
vault_1     | I1221 02:18:30.686384      11 pg.go:148] successfully connected to postgres vault-db:5432
vault_1     | I1221 02:18:30.692238      11 jwt.go:42] ===== USING given JWT secret ====
vault_1     | panic: open /grpc/server/server.crt: no such file or directory
vault_1     | 
vault_1     | goroutine 1 [running]:
vault_1     | github.com/lainio/err2.Check(...)
vault_1     | 	/go/pkg/mod/github.com/lainio/err2@v0.6.1/err2.go:34
vault_1     | github.com/findy-network/findy-common-go/agency/client.TryAuthOpen(0x0, 0x0, 0xc0001a6bc0, 0x4, 0xc383)
vault_1     | 	/go/pkg/mod/github.com/findy-network/findy-common-go@v0.1.7-0.20210527125553-4a46a2db405d/agency/client/client.go:69 +0x137
vault_1     | github.com/findy-network/findy-agent-vault/agency/findy.(*Agency).Init(0xc000110d20, 0xd937c8, 0xc00000f458, 0x120b610, 0x0, 0x0, 0xd8d298, 0xc000135dd0, 0xc0001aa000)
vault_1     | 	/work/agency/findy/agency.go:51 +0x14d
vault_1     | github.com/findy-network/findy-agent-vault/resolver.InitResolverWithDB(0xc0001aa000, 0xd92608, 0xc000110d20, 0xd99638, 0xc000010818, 0xc5d0a0)
vault_1     | 	/work/resolver/resolver.go:91 +0x874
vault_1     | github.com/findy-network/findy-agent-vault/resolver.InitResolver(0xc0001aa000, 0xd92608, 0xc000110d20, 0xc000000180)
vault_1     | 	/work/resolver/resolver.go:101 +0x75
vault_1     | main.main()
vault_1     | 	/work/main.go:27 +0xc5
findy-agent_vault_1 exited with code 2

Have checked the findy-agent-cli repo and there seems to be a server.crt file but not in the config directory on my local machine ?

Apologies is there are any prerequisite steps (initialisation) that I might have missed...

(Build from source works well however)

**Comment by techlab-lainio** [comment]
Thank you for your update!

Unfortunately, I wasn't able to reproduce the error. I did start the docker-compose system in `findy-wallet-pwa/tools/env` by using the `Makefile` and its rules. I also did try bot on macOS and Linux with the latest versions. All worked OK.

The only tip or advice I could think of from the logs you submitted is some problem with the docker volumes. For example, the core-agency (`core_1`) should produce these lines also when started in the very first time:
```
core_1      | Creating ledger handle...
core_1      | /root/.indy_client/wallet/steward/ does not exist, importing wallet
core_1      | wallet steward imported from file /steward.exported
core_1      | W1221 07:07:41.774132      25 enclave.go:51] init enclave WITHOUT a key /root/.indy_client/enclave.bolt
core_1      | Processing starts, please wait..
core_1      | Processing done
core_1      | Saving starts
core_1      | All ready
```
The steward wallet is created to mounted volume `.data` and there into the location `/agent/.indy_client/wallet`.

A similar issue seems to be with the `vault`. It doesn't find TLS certificate files for the gRPC connection.

Because of the Christmas season, everyone uses their vacation, so I'm afraid that we will get back to this until next year. However, I'll get back to you as soon as I get new information.

Merry Christmas and Happy New Year!

**Comment by lauravuo-techlab** [comment]
Thanks for your feedback @paul-yellowpink! Just to make sure, were you following [these steps](https://github.com/findy-network/findy-wallet-pwa/tree/dev/tools/env#agency-setup-for-local-development) for setting up the docker environment?

**Comment by paul-yellowpink** [comment]
Thanks @techlab-lainio & @lauravuo-techlab - I'll retry with the PWA install steps and double check both install diffs (and close with comments)

Happy Holidays !!!

**Comment by paul-yellowpink** [comment]
Apologies for the delay in closing this - all good now, and thanks for your help !
