### ISSUE TITLE
invalid key created by "findy-agent tools key create"

### ISSUE THREAD

**Issue by sschulz-t** [findy-network/findy-agent#274]
**Describe the bug**
The returned password of 
findy-agent tools key create 
is invalid (only 43 characters instead of 44). 
This key is not accepted by e.g. findy-agent ledger steward create

**To Reproduce**
1. run 'findy-agent tools key create' multiple times (sometimes it takes quite long to produce a bad one) 

**Expected behavior**
All passwords should contain 44 chars.

**Wrong output**
$ findy-agent tools key create
7b4xLTF2RrgDrSfRudhYJMprYSR2UrAZYH3Ks2dJsZNv <-- 44 characters

$ findy-agent tools key create
4oc2FfGv4bx3RqJ3cm3psb38iphhG368zpE2QjufKzao <-- 44 characters

$ findy-agent tools key create
YbNRqv46mwsX2joqTLfxAFhDR9Jq4JT5q7qRLFt4qmw  <-- 43 characters!

**Comment by lainio** [comment]
Thank you for the report!

I managed to reproduce the 43-character wallet key with and without the seed. We are using `libindy` to generate the key. The 43-length key is valid but rare, so our other commands that accept wallet keys should also take that key length.

I'll continue with this tomorrow and let you know how it goes 👍

**Comment by lainio** [comment]
Fixed on PR #276. Closing the issue.
